### ISSUE TITLE
Error is general JS error, should be Axios error

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-auth-js#8]
Current errors returned are generic Errors but should be Axios specific errors (https://github.com/axios/axios/blob/6b4fd93e6886c281ef1a51fca556616ce17f8fba/index.d.ts#L124-L131).

**Comment by moneebalalfi** [comment]
@elitan  
Thank you for adding this issue .. something important especially when we are using typescript, any plans when it will be solved?
